name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["enhancement", "feature"]
  - title: "🐞 Fixes"
    labels: ["bug"]
  - title: "📝 Docs"
    labels: ["documentation"]
  - title: "⚙️ CI"
    labels: ["ci"]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes
  $CHANGES
