extends: default

rules:
  braces: disable # убираем "too many spaces inside braces"
  line-length: disable # игнорируем длину строки
  trailing-spaces: disable # игнорируем хвостовые пробелы
  indentation:
    spaces: 2 # оставим базовую проверку отступов (без фанатизма)
    indent-sequences: consistent
  document-start: disable # не требуем '---'
  truthy:
    check-keys: false # 'on'/'off' и т.п. — норм
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

ignore: |
  _site/**
  node_modules/**
  .quarto/**
  **/*.md
  **/*.qmd
  # если нужно полностью исключить служебные файлы CI:
  # .github/**
