# filename: _quarto-fr.yml

project:
  pre-render:
    - python scripts/select_snippets.py
  render:
    - fr/index.qmd
    - fr/linux.qmd
    - fr/docker.qmd
    - fr/git.qmd
    - fr/kubernetes.qmd
    - fr/helm.qmd
    - fr/terraform.qmd
    - fr/about.qmd

lang: fr-FR

metadata-files:
  - locales/fr-fr/_site.yml
  - locales/fr-fr/linux.yml
  - locales/fr-fr/docker.yml
  - locales/fr-fr/git.yml
  - locales/fr-fr/kubernetes.yml
  - locales/fr-fr/helm.yml
  - locales/fr-fr/terraform.yml
  - locales/fr-fr/about.yml

website:
  title: "Aide-mémoire DevOps"
  sidebar:
    search: true
    contents:
      - fr/index.qmd
      - fr/linux.qmd
      - fr/docker.qmd
      - fr/git.qmd
      - fr/kubernetes.qmd
      - fr/helm.qmd
      - fr/terraform.qmd
  navbar:
    logo: assets/brand/fr/hackitect7-logo-light-fr.png
    logo-alt: "Logo Hackitect7 (fr)"
    left:
      - text: "Accueil"
        href: /
      - text: "Aide"
        menu:
          - text: "Signaler un bug"
            icon: "bug"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/issues"
          - text: "Poser une question"
            icon: "chat-right-text"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/discussions"
      - text: "À propos"
        href: fr/about.qmd
