# filename: _quarto-vn.yml

project:
  render:
    - vn/index.qmd
    - vn/linux.qmd
    - vn/docker.qmd
    - vn/git.qmd
    - vn/kubernetes.qmd
    - vn/helm.qmd
    - vn/terraform.qmd
    - vn/about.qmd

lang: vi-VN

metadata-files:
  - locales/vi-vn/_site.yml
  - locales/vi-vn/linux.yml
  - locales/vi-vn/docker.yml
  - locales/vi-vn/git.yml
  - locales/vi-vn/kubernetes.yml
  - locales/vi-vn/helm.yml
  - locales/vi-vn/terraform.yml
  - locales/vi-vn/about.yml

website:
  title: "Bảng tóm tắt DevOps"
  sidebar:
    search: true
    contents:
      - vn/index.qmd
      - vn/linux.qmd
      - vn/docker.qmd
      - vn/git.qmd
      - vn/kubernetes.qmd
      - vn/helm.qmd
      - vn/terraform.qmd
  navbar:
    logo: assets/brand/vn/hackitect7-logo-light-vn.png
    logo-alt: "Logo Hackitect7 (vi-VN)"
    left:
      - text: "Trang chủ"
        href: /
      - text: "Hỗ trợ"
        menu:
          - text: "Báo cáo lỗi"
            icon: "bug"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/issues"
          - text: "Đặt câu hỏi"
            icon: "chat-right-text"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/discussions"
      - text: "Giới thiệu"
        href: vn/about.qmd
