# filename: _quarto-id.yml

project:
  pre-render:
    - python scripts/select_snippets.py
  render:
    - id/index.qmd
    - id/linux.qmd
    - id/docker.qmd
    - id/git.qmd
    - id/kubernetes.qmd
    - id/helm.qmd
    - id/terraform.qmd
    - id/about.qmd

lang: id-ID

metadata-files:
  - locales/id-id/_site.yml
  - locales/id-id/linux.yml
  - locales/id-id/docker.yml
  - locales/id-id/git.yml
  - locales/id-id/kubernetes.yml
  - locales/id-id/helm.yml
  - locales/id-id/terraform.yml
  - locales/id-id/about.yml

website:
  title: "Lembar Pintasan DevOps"
  sidebar:
    search: true
    contents:
      - id/index.qmd
      - id/linux.qmd
      - id/docker.qmd
      - id/git.qmd
      - id/kubernetes.qmd
      - id/helm.qmd
      - id/terraform.qmd
  navbar:
    logo: assets/brand/id/hackitect7-logo-light-id.png
    logo-alt: "Logo Hackitect7 (id-ID)"
    left:
      - text: "Beranda"
        href: /
      - text: "Bantuan"
        menu:
          - text: "Laporkan Bug"
            icon: "bug"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/issues"
          - text: "Ajukan Pertanyaan"
            icon: "chat-right-text"
            href: "https://github.com/Hackitect7/devops-cheat-sheet/discussions"
      - text: "Tentang"
        href: id/about.qmd
