# filename: _quarto.yml

project:
  type: website
  output-dir: _site
  pre-render:
    - python scripts/select_snippets.py
  render:
    - index.qmd
  resources:
    - assets/**

date: last-modified
highlight-style: a11y

metadata:
  description: "Multilingual DevOps cheat sheet: Linux, Docker, Git, Kubernetes, Helm, Terraform, practical scenarios & templates."
  image: assets/brand/us/hackitect7-og.png
  image-alt: "DevOps Cheat Sheet — logo and tagline"

website:
  favicon: assets/brand/favicon.svg
  site-url: https://hackitect7.github.io/devops-cheat-sheet
  open-graph: true
  twitter-card: true
  page-navigation: true
  reader-mode: true
  bread-crumbs: false
  navbar:
    search: true
    collapse-below: xl
    background: light
    title: false
    tools:
      - icon: github
        href: https://github.com/Hackitect7/devops-cheat-sheet
        text: Hackitect7 GitHub

format:
  html:
    canonical-url: true
    link-external-newwindow: true
    link-external-icon: true
    respect-user-color-scheme: true
    toc: true
    smooth-scroll: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    highlight-style: github
    css:
      - assets/css/styles.css
      - https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/7.5.0/css/flag-icons.min.css
    include-after-body:
      - assets/js/tweaks.html
    anchor-sections: true
    lib-dir: site_libs
