name: "📝 Docs/content improvement"
description: Fix typos, structure, style, examples
labels: ["documentation"]
body:
  - type: input
    id: page
    attributes:
      label: Page / section
      placeholder: /us/docker/..., /ru/k8s/...
      description: Relative path or URL
  - type: textarea
    id: change
    attributes:
      label: What to change
      placeholder: Current vs proposed text, reasons
    validations:
      required: true
