name: "✨ Feature request"
description: Suggest a new page, block, or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      placeholder: What pain are we solving?
      description: Why is this important?
      value: |
        As a <role>, I want <capability>, so that <benefit>.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Outline of content, structure, examples.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: input
    id: locale
    attributes:
      label: Target locales
      placeholder: en-US, ru-RU, ...
