name: Lint & Check
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      # Node + кэш npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      # Prettier (формат)
      - name: Prettier
        run: npm run format:check

      # Stylelint (CSS/SCSS + inline CSS в HTML/MD/QMD)
      - name: Stylelint
        run: npm run lint:css

      # YAMLLint
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
          config_file: ".yamllint.yaml"
          strict: true

      # Markdownlint (включая .qmd)
      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: "**/*.{md,qmd}"
          config_file: ".markdownlint.yaml"

      # Smoke-render для линк-чекера
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # (опционально) Кэш Quarto чтобы ускорить рендер
      - name: Cache Quarto
        uses: actions/cache@v4
        with:
          path: ~/.quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('**/*.qmd', '**/*.yml', '**/*.yaml', '**/*.scss', '**/*.css') }}

      - name: Render (smoke)
        run: quarto render index.qmd

      # Link Checker — по сгенерированным HTML
      - name: Link Checker (_site)
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose --no-progress
            --accept 200,206,429
            --max-retries 2
            --retry-wait-time 2
            --max-concurrency 8
            --timeout 20
            --exclude-mail
            --exclude "https://github.com/Hackitect7/devops-cheat-sheet/issues/new.*"
            "_site/**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
