name: Release Drafter

on:
  push:
    branches: ["main"] # обновлять драфт при пушах в main
  pull_request: # и при событиях на PR
    types:
      - opened
      - reopened
      - synchronize
      - edited # поменяли заголовок/описание
      - labeled # навесили лейблы
      - unlabeled # сняли лейблы
      - ready_for_review # из draft → ready
  workflow_dispatch: # запуск вручную

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
